services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      
      - ./client:/app
      
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
